### ISSUE TITLE
HTML Overridden

### ISSUE THREAD

**Issue by IanMinash** [ScottBarkman/vscode-djaneiro#15]
Hello, when I enable this extension in VSCode HTML tags no longer autocomplete

**Comment by aubricus** [comment]
I am seeing the same issue. Had to uninstall. 😢 

VSCode Version: 1.23.1
OS: MacOS 10.13.3
Djanerio Version: 1.4.1
Install Method: Extensions Marketplace > Install

**Comment by ScottBarkman** [comment]
I just deployed a fix. 

I moved the django grammer into its own language, and reverted back to using html as the default.

**Comment by IanMinash** [comment]
Thanks, working well now
