### ISSUE TITLE
Snippets not working when within quotes

### ISSUE THREAD

**Issue by gauravsatish** [ScottBarkman/vscode-djaneiro#25]
The pop-up for autocompletion does not come when the cursor is within a string.
For example:
`<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">`
When I go into the "href" attribute and type static(which works fine when outside a string), the autocomplete option does not appear.

**Comment by gauravsatish** [comment]
Oh nope, don't worry, i understood why it was not working.
It was because I was using this other package that did HTML autocomplete, but I fixed it
So no worries

**Comment by MbBrainz** [comment]
Hi, i have tis issue as well. How did you fix it?
