### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by sebastian-code** [ScottBarkman/vscode-djaneiro#6]
At this moment the snippets are designed to construct code mainly focused on Python 2, are you planning to support Python3 as default?

A good example is on the models snippets, where the plugin creates the string representation of the model as `def __unicode__(self):` which is deprecated in Python 3 and replaced with `def __str__(self):`. To keep the Python 2 compatibility, you can add the decorator `@python_2_unicode_compatible` on top of the model and the proper import `from django.utils.encoding import python_2_unicode_compatible` on the import block.

**Comment by ScottBarkman** [comment]
Yea, those methods have been nagging at me for a while. I don't feel we need to necessarily support Python 2 at this point, they've had enough to time to adapt ;)

**Comment by sebastian-code** [comment]
Perhaps the approach of implementing backwards compatibility to Python 2 using `futures` and other libraries.

**Comment by ScottBarkman** [comment]
I'd just rather not have to force everyone to include an import manually when triggering a snippet. I'd sooner just drop Python 2 support all together.

**Comment by sebastian-code** [comment]
On that I agree with you.

**Comment by sebastian-code** [comment]
Solved on #9 closing the Issue.
